/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as BooksBooksRouteImport } from './routes/books/books'
import { Route as BooksAuthorsRouteImport } from './routes/books/authors'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as DemoUsersAddUserRouteImport } from './routes/demo/users/add-user'
import { Route as DemoUsersIdRouteImport } from './routes/demo/users/$id'
import { Route as DemoProductsProductsRouteImport } from './routes/demo/products/products'
import { Route as DemoProductsProductIdRouteImport } from './routes/demo/products/$productId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBooksRoute = BooksBooksRouteImport.update({
  id: '/books/books',
  path: '/books/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksAuthorsRoute = BooksAuthorsRouteImport.update({
  id: '/books/authors',
  path: '/books/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUsersAddUserRoute = DemoUsersAddUserRouteImport.update({
  id: '/demo/users/add-user',
  path: '/demo/users/add-user',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUsersIdRoute = DemoUsersIdRouteImport.update({
  id: '/demo/users/$id',
  path: '/demo/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProductsProductsRoute = DemoProductsProductsRouteImport.update({
  id: '/demo/products/products',
  path: '/demo/products/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProductsProductIdRoute = DemoProductsProductIdRouteImport.update({
  id: '/demo/products/$productId',
  path: '/demo/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/books/$id': typeof BooksIdRoute
  '/books/authors': typeof BooksAuthorsRoute
  '/books/books': typeof BooksBooksRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/products/$productId': typeof DemoProductsProductIdRoute
  '/demo/products/products': typeof DemoProductsProductsRoute
  '/demo/users/$id': typeof DemoUsersIdRoute
  '/demo/users/add-user': typeof DemoUsersAddUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/books/$id': typeof BooksIdRoute
  '/books/authors': typeof BooksAuthorsRoute
  '/books/books': typeof BooksBooksRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/products/$productId': typeof DemoProductsProductIdRoute
  '/demo/products/products': typeof DemoProductsProductsRoute
  '/demo/users/$id': typeof DemoUsersIdRoute
  '/demo/users/add-user': typeof DemoUsersAddUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/books/$id': typeof BooksIdRoute
  '/books/authors': typeof BooksAuthorsRoute
  '/books/books': typeof BooksBooksRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/products/$productId': typeof DemoProductsProductIdRoute
  '/demo/products/products': typeof DemoProductsProductsRoute
  '/demo/users/$id': typeof DemoUsersIdRoute
  '/demo/users/add-user': typeof DemoUsersAddUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/books/$id'
    | '/books/authors'
    | '/books/books'
    | '/demo/prisma'
    | '/demo/products/$productId'
    | '/demo/products/products'
    | '/demo/users/$id'
    | '/demo/users/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/books/$id'
    | '/books/authors'
    | '/books/books'
    | '/demo/prisma'
    | '/demo/products/$productId'
    | '/demo/products/products'
    | '/demo/users/$id'
    | '/demo/users/add-user'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/books/$id'
    | '/books/authors'
    | '/books/books'
    | '/demo/prisma'
    | '/demo/products/$productId'
    | '/demo/products/products'
    | '/demo/users/$id'
    | '/demo/users/add-user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BooksIdRoute: typeof BooksIdRoute
  BooksAuthorsRoute: typeof BooksAuthorsRoute
  BooksBooksRoute: typeof BooksBooksRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoProductsProductIdRoute: typeof DemoProductsProductIdRoute
  DemoProductsProductsRoute: typeof DemoProductsProductsRoute
  DemoUsersIdRoute: typeof DemoUsersIdRoute
  DemoUsersAddUserRoute: typeof DemoUsersAddUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/books': {
      id: '/books/books'
      path: '/books/books'
      fullPath: '/books/books'
      preLoaderRoute: typeof BooksBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/authors': {
      id: '/books/authors'
      path: '/books/authors'
      fullPath: '/books/authors'
      preLoaderRoute: typeof BooksAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/users/add-user': {
      id: '/demo/users/add-user'
      path: '/demo/users/add-user'
      fullPath: '/demo/users/add-user'
      preLoaderRoute: typeof DemoUsersAddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/users/$id': {
      id: '/demo/users/$id'
      path: '/demo/users/$id'
      fullPath: '/demo/users/$id'
      preLoaderRoute: typeof DemoUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/products/products': {
      id: '/demo/products/products'
      path: '/demo/products/products'
      fullPath: '/demo/products/products'
      preLoaderRoute: typeof DemoProductsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/products/$productId': {
      id: '/demo/products/$productId'
      path: '/demo/products/$productId'
      fullPath: '/demo/products/$productId'
      preLoaderRoute: typeof DemoProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BooksIdRoute: BooksIdRoute,
  BooksAuthorsRoute: BooksAuthorsRoute,
  BooksBooksRoute: BooksBooksRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoProductsProductIdRoute: DemoProductsProductIdRoute,
  DemoProductsProductsRoute: DemoProductsProductsRoute,
  DemoUsersIdRoute: DemoUsersIdRoute,
  DemoUsersAddUserRoute: DemoUsersAddUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
